#!/usr/bin/env python3
"""Generate the RTS delegate bridge. Python standard library only."""
import argparse
import json
from pathlib import Path
import re
import sys
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[2]
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
# Deliberately limited contract grammar; never silently parse arbitrary C#.
TYPE = re.compile(r"(?:float|double|int|long|bool|string|IMyCubeGrid)(?:\[\])?\Z")


def validate(contract):
    for key in ("client", "provider"):
        if not IDENTIFIER.fullmatch(contract[key]):
            raise ValueError("Invalid identifier: " + key)
    if not all(IDENTIFIER.fullmatch(p) for p in contract["namespace"].split(".")):
        raise ValueError("Invalid namespace")
    channel = contract["channel"]
    if type(channel) is not int or not -(2**63) <= channel < 2**63:
        raise ValueError("Channel must be a signed 64-bit integer")
    if not re.fullmatch(r"[A-Za-z0-9 ._-]+", contract["displayName"]):
        raise ValueError("Invalid display name")
    names = set()
    reserved = {"Load", "Unload", "IsReady", "HandleMessage", "EnsureReady", "AssignMethod", contract["client"]}
    if not contract["methods"]:
        raise ValueError("Contract must have methods")
    for method in contract["methods"]:
        name = method["name"]
        if not IDENTIFIER.fullmatch(name) or name in names or name in reserved:
            raise ValueError("Invalid or duplicate method: " + name)
        names.add(name)
        if not IDENTIFIER.fullmatch(method.get("providerMethod", name)):
            raise ValueError("Invalid provider method: " + name)
        if method["returns"] != "void" and not TYPE.fullmatch(method["returns"]):
            raise ValueError("Unsupported return type: " + name)
        parameters = method["parameters"]
        if len(parameters) > 16:
            raise ValueError("Delegates support at most 16 parameters")
        parameter_names = set()
        for parameter in parameters:
            if not IDENTIFIER.fullmatch(parameter["name"]) or parameter["name"] in parameter_names:
                raise ValueError("Invalid or duplicate parameter: " + name)
            parameter_names.add(parameter["name"])
            if not TYPE.fullmatch(parameter["type"]):
                raise ValueError("Unsupported parameter type: " + name)


def render(contract):
    validate(contract)
    clear, bind, assignments, methods, registrations = [], [], [], [], []
    for method in contract["methods"]:
        name, result = method["name"], method["returns"]
        parameters = method["parameters"]
        types = [p["type"] for p in parameters]
        delegate = "Action" if result == "void" else "Func"
        if result != "void":
            types.append(result)
        if types:
            delegate += "<" + ", ".join(types) + ">"
        signature = ", ".join(p["type"] + " @" + p["name"] for p in parameters)
        arguments = ", ".join("@" + p["name"] for p in parameters)
        clear.append(f"            _{name} = null;")
        bind.extend([f"            {delegate} bound{name} = null;",
                     f'            AssignMethod(dict, "{name}", ref bound{name});'])
        assignments.append(f"            _{name} = bound{name};")
        documentation = "\n".join("        /// " + escape(line) for line in method["summary"].splitlines())
        returned = "" if result == "void" else "return "
        methods.append(f"        /// <summary>\n{documentation}\n        /// </summary>\n"
                       f"        public {result} {name}({signature}) {{ EnsureReady(); {returned}_{name}.Invoke({arguments}); }}\n"
                       f"        private {delegate} _{name};")
        provider_method = method.get("providerMethod", name)
        registrations.append(f'                ["{name}"] = new {delegate}(RTS.@{provider_method}),')
    values = {
        "CHANNEL": str(contract["channel"]), "NAMESPACE": contract["namespace"],
        "CLIENT": contract["client"], "PROVIDER": contract["provider"],
        "DISPLAY_NAME": contract["displayName"], "CLEAR": "\n".join(clear),
        "BIND": "\n".join(bind + assignments), "METHODS": "\n\n".join(methods),
        "REGISTRATIONS": "\n".join(registrations),
    }
    outputs = {}
    for template, suffix in (("consumer", ".cs"), ("backend", "Backend.cs")):
        source = (ROOT / "tools/api/templates" / (template + ".cs.txt")).read_text()
        source = re.sub(r"@@([A-Z_]+)@@", lambda match: values[match[1]], source)
        header = "// <auto-generated>\n// From api/rts.json and tools/api/templates. Do not edit.\n// Run: python3 tools/api/generate.py\n// </auto-generated>\n"
        outputs[ROOT / "RelativeTopSpeed" / (contract["client"] + suffix)] = header + source
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if checked-in output is stale; do not write")
    args = parser.parse_args()
    contract = json.loads((ROOT / "api/rts.json").read_text())
    outputs = render(contract)
    stale = []
    for path, source in outputs.items():
        if path.exists() and path.read_bytes() == source.encode("utf-8"):
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.write_bytes(source.encode("utf-8"))
    if args.check and stale:
        print("Stale generated API files: " + ", ".join(map(str, stale)), file=sys.stderr)
        print("Run python3 tools/api/generate.py", file=sys.stderr)
        return 1
    print("API bindings are up to date." if not stale else "Generated: " + ", ".join(map(str, stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
